# Generated by Django 4.1.5 on 2023-02-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('type_user', models.CharField(choices=[('Admin', 'admin'), ('User', 'user'), ('Editor', 'editor')], default='User', max_length=9)),
                ('photo', models.ImageField(default='images/default/no-img.jpg', upload_to='images/')),
            ],
        ),
    ]
